### ISSUE TITLE
Huge Lag in iPhone X

### ISSUE THREAD

**Issue by SriKrishnaCovalense** [alankarmisra/SwiftSignatureView#21] opened 2018-08-21 10:09 UTC
Good Afternoon,

I am using this library over a pet project, and found that in iPhone X its having huge lag, say if i write 3 Letters, the Signing starts at First Letter.

Can you please try to reproduce the same and please release it in a patch.

Thanks!

**Comment by SriKrishnaCovalense** [comment] 2018-08-28 08:47
Any update on this issue will be helpful.

**Comment by ergunkocak** [comment] 2018-10-15 09:32
Could not reproduce in iPhoneX with IOS 11.4.1

**Comment by alankarmisra** [comment] 2019-06-07 04:40
I've tried this on iPhone X and iPhone XS Max and it seems to be ok. I did notice an occassional lag in the simulator but never on the real device. I'm closing this issue for now but if you still find it lagging, feel free to reopen the issue.

**Closed by alankarmisra** 2019-06-07 04:40 UTC
